### ISSUE TITLE
Results Page

### ISSUE THREAD

**Issue by jack-elliott** [mI-PIV/app#410]
One last round of revisions for the results page. We can discuss this image in our meeting (i'll email in case the upload didn't work)

![resultspage feedback](https://user-images.githubusercontent.com/77805273/191065429-ffc9f6cc-0db1-457e-b0ed-c5485721a0a0.png)

- [x] round all information to 1 decimal place
- [x] place X and Y under Details
- [x] Move U and V below the X and Y (in details) and above vorticity
- [x] correct units for no calibration (all results should be in pixels, pixels/framerate, or 1/framerate
- [x] correct units for calibration (all results should be in cm, cm/s, or 1/s)
- [x] correct units in conversion factor(s)
- [x] add the temporal conversion factor as "time" factor (more accessible)

**Comment by kp-121** [comment]
@jack-elliott I wanted you to take a look before I make a release.
A couple of things: I made the time conversion factor 2 decimal places because it kept showing "0.0 s". Also, I know the XY values in the non-calibrated are wrong and I will fix it before the release.

![Screenshot_20220919-170303_mI-PIV](https://user-images.githubusercontent.com/20914336/191134417-92071dda-db59-4114-a197-fab32cd5c504.jpg)
![Screenshot_20220919-170159_mI-PIV](https://user-images.githubusercontent.com/20914336/191134425-7e9f7a3e-3adf-423d-b4c6-9864d86998a9.jpg)

**Comment by jack-elliott** [comment]
Hey Kris,
This is great. A couple thoughts:
let's put a newline between the *velocity* and actual values, so it matches
the other half.
For the time, ya let's actually make it go to 4 decimals. I didn't think
about that.
let's put the vorticity above the conversions and below the U v.
let's change "framerate" to frame. Just to avoid any weirdness.

**Comment by jack-elliott** [comment]
Sorry! Let's add s/frame to the time conversion units, rather than just s.
